location="eastus"
resource_group_name="rg-p-state-wp-eus"
workload_name="wp-state"
subscription_id="b1e58f5f-6586-4090-b9f3-a3e25e7544e0"
environment="p"
naming_convention="{resourceType}-{environment}-{workloadName}-{region}"